/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laporan;

/**
 *
 * @author baisy
 */
public class FormCetakLaporan extends javax.swing.JFrame {

    /**
     * Creates new form FormCetakLaporan
     */
    public FormCetakLaporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jButton1)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jButton1)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Deklarasi variabel sesuai materi
        String user="root";
        String pass="";
        String host="localhost";
        String db="mhs";
        String url="";
        java.io.File dir1=new java.io.File(".");
        String dirr="";

        try {
            // Pengaturan driver untuk MySQL versi baru
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pass;
            java.sql.Connection conn=(java.sql.Connection) java.sql.DriverManager.getConnection(url);
            
            java.sql.Statement st = (java.sql.Statement) conn.createStatement();

            // Mengambil file desain dari folder laporan
            dirr=dir1.getCanonicalPath()+"/src/laporan/";
            net.sf.jasperreports.engine.design.JasperDesign disain = net.sf.jasperreports.engine.xml.JRXmlLoader.load(dirr+"report1.jrxml");
            net.sf.jasperreports.engine.JasperReport nilaiLaporan = net.sf.jasperreports.engine.JasperCompileManager.compileReport(disain);
            
            // Eksekusi query
            java.sql.ResultSet rs = st.executeQuery("SELECT * FROM datamhs ");
            net.sf.jasperreports.engine.JRResultSetDataSource resultSetDataSource = new net.sf.jasperreports.engine.JRResultSetDataSource(rs);
            
            // Proses cetak
            net.sf.jasperreports.engine.JasperPrint cetak = net.sf.jasperreports.engine.JasperFillManager.fillReport(nilaiLaporan, new java.util.HashMap(), resultSetDataSource);
            
            // Menampilkan laporan
            net.sf.jasperreports.view.JasperViewer.viewReport(cetak, false);

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null,"Gagal mencetak\n" +ex,"Kesalahan",javax.swing.JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCetakLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCetakLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCetakLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCetakLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCetakLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
